# Redirect HTTP -> HTTPS
server {
    listen 80;
    server_name diffan.dev www.diffan.dev lovelypet.diffan.dev grafana.diffan.dev;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# 1. Main Web Resume
server {
    listen 443 ssl;
    server_name diffan.dev www.diffan.dev;

    ssl_certificate /etc/letsencrypt/live/diffan.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/diffan.dev/privkey.pem;

    location / {
        proxy_pass http://web-resume:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# 2. Lovelypet Subdomain
server {
    listen 443 ssl;
    server_name lovelypet.diffan.dev;

    ssl_certificate /etc/letsencrypt/live/diffan.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/diffan.dev/privkey.pem;

    location / {
        proxy_pass http://lovelypet:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# 3. Grafana Subdomain
server {
    listen 443 ssl;
    server_name grafana.diffan.dev;

    ssl_certificate /etc/letsencrypt/live/diffan.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/diffan.dev/privkey.pem;

    location / {
        proxy_pass http://grafana:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}